### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by alejandro-anv** [openchange/openchange#406]
I am following this instructions  http://www.openchange.org/documentation/howto/zentyal_developer.html for updating a zentyal server. The compilation process report various warnings and finally aborts with mapiproxy/dcesrv_mapiproxy.c:137:5: error: dereferencing pointer to incomplete type

I think it is may be a samba version problem. ( 4.3.1 is installed) Any help please?

<pre>
Compiling utils/rpcextract.c
Linking bin/rpcextract
Compiling mapiproxy/dcesrv_mapiproxy.c with -fPIC
mapiproxy/dcesrv_mapiproxy.c: In function ‘mapiproxy_op_connect’:
mapiproxy/dcesrv_mapiproxy.c:137:5: error: dereferencing pointer to incomplete type
    b->assoc_group_id = dce_call->pkt.u.bind.assoc_group_id;
     ^
mapiproxy/dcesrv_mapiproxy.c:140:5: error: dereferencing pointer to incomplete type
    b->assoc_group_id = dce_call->pkt.u.alter.assoc_group_id;
     ^
mapiproxy/dcesrv_mapiproxy.c:157:55: error: ‘struct dcerpc_pipe’ has no member named ‘assoc_group_id’
   dce_call->context->assoc_group->id = private->c_pipe->assoc_group_id;
                                                       ^
mapiproxy/dcesrv_mapiproxy.c:172:55: error: ‘struct dcerpc_pipe’ has no member named ‘assoc_group_id’
   dce_call->context->assoc_group->id = private->c_pipe->assoc_group_id;
                                                       ^
mapiproxy/dcesrv_mapiproxy.c: In function ‘mapiproxy_op_bind’:
mapiproxy/dcesrv_mapiproxy.c:230:2: warning: implicit declaration of function ‘server_id_str’ [-Wimplicit-function-declaration]
  server_id_printable = server_id_str(NULL, &(dce_call->conn->server_id));
  ^
mapiproxy/dcesrv_mapiproxy.c:230:22: warning: assignment makes pointer from integer without a cast [enabled by default]
  server_id_printable = server_id_str(NULL, &(dce_call->conn->server_id));
                      ^
mapiproxy/dcesrv_mapiproxy.c: At top level:
mapiproxy/dcesrv_mapiproxy.c:735:13: warning: ‘dcesrv_mapiproxy_lp_defaults’ defined but not used [-Wunused-function]
 static bool dcesrv_mapiproxy_lp_defaults(struct loadparm_context *lp_ctx)
             ^
make: *** [mapiproxy/dcesrv_mapiproxy.po] Error 1
</pre>

**Comment by sixstone-qq** [comment]
Use zentyal/openchange repository master branch as it is working with samba 4.3

https://github.com/Zentyal/openchange/

**Comment by blaxter** [comment]
Current openchange/openchange master branch only works for samba 4.1.x, use zentyal/openchange repo if you are with samba 4.3.x
